### ISSUE TITLE
Movement

### ISSUE THREAD

**Issue by GodModed** [Sparky983/diorite#1]
Add movement

**Comment by Sparky983** [comment]
I'm currently thinking about how I could implement a clean API for such a thing. 

I was thinking maybe you could chain a bunch of movement methods which would execute 1 by 1 every tick until no more are left. 

```java
DioriteClient client = ...;

client.move()
        .by(Vector.of(1, 1, 1)) // relative
        .to(Position.of(10, 10, 10))  // absolute
        .block() // block until movement is finished
```

Any ideas?

**Comment by GodModed** [comment]
Fax

**Comment by GodModed** [comment]
Any updates?

**Comment by Sparky983** [comment]
> Any updates?

No, I haven't been doing much on here lately. If you would like to make a PR, I'd still review that though.

**Comment by GodModed** [comment]
I will not be making a pull request.
